name: "LLNL Jekyll Template"
author: "Ian Lee <lee1001@llnl.gov>"
description: "LLNL Jekyll Template"

url: "http://localhost:4000"

# paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments
