name: "MacPatch"
author: "Jorge Escobar <escobar6@llnl.gov>"
description: "OS X Management Software"

url: "http://macpatch.llnl.gov"
baseurl: ""

collections:
  documentation:
    output: true
    permalink: /documentation/:path/

# paginate: 10

markdown: kramdown
permalink: pretty
highlighter: pygments
