name: "MacPatch"
author: "Jorge Escobar <escobar6@llnl.gov>"
description: "OS X Management Software"

url: "http://macpatch.llnl.gov"


img_path: "/assets/images"

collections:
  docs:
    output: true
    permalink: /:path/

# paginate: 10

markdown: kramdown
permalink: pretty
highlighter: pygments
