name: "MacPatch"
author: "Jorge Escobar <escobar6@llnl.gov>"
description: "OS X Management Software"

url: "http://macpatch.llnl.gov"
baseurl: ""

img_media: /static/assets/main/images 

collections:
  docs:
    output: true
    permalink: /docs/:path/

# paginate: 10

permalink: pretty
